apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # deployement labels
  labels:
    purpose: Ingress
    project: roboshop
    app: app1
spec:
  replicas: 1
  # this are the labels replica set to use create pod replicas, this should match the pod labels
  selector:
    matchLabels:
      purpose: Ingress
      project: roboshop
      app: app1
# This is pod defination
  template:
    metadata:
      labels:
        purpose: Ingress
        project: roboshop
        app: app1
    spec:
      containers:
      - name: nginx
        image: shivanathbabu/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  labels:
    purpose: Ingress
    project: roboshop
    app: app1
spec:
  selector:
    purpose: Ingress
    project: roboshop
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:139355608147:certificate/be127313-e26a-4faa-abb5-e1263cd394e4
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip  
    alb.ingress.kubernetes.io/group.name: shivanathbabu
spec:
  ingressClassName: alb
  rules:
  - host: "app1.teshome.online"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80
  
