apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    purpose: deployement-demo
    project: roboshop
    app: Ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: deployement-demo
      project: roboshop
      app: Ingress
  template:
    metadata:
      labels:
        purpose: deployement-demo
        project: roboshop
        app: Ingress
    spec:
      containers:
      - name: nginx
        image: shivanathbabu/app2:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    purpose: deployement-demo
    project: roboshop
    app: Ingress
spec:
  selector:
    purpose: deployement-demo
    project: roboshop
    app: Ingress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:139355608147:certificate/be127313-e26a-4faa-abb5-e1263cd394e4
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: shivanathbabu
spec:
  ingressClassName: alb
  rules:
  - host: "app2.teshome.online"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80
  


  